apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Apofenic.github.io
  description: for tech docs. 
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: development
  owner: guests
